- name: Checkout
  uses: actions/checkout@v4.1.1

  uses: game-ci/unity-test-runner@v4
  env:
    UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
  with:
    projectPath: /"Dungeon Crawler"
    githubToken: ${{ secrets.GITHUB_TOKEN }}

