name: Actions 😎

on: [push, pull_request]

jobs:
  lint:
    name: Test lint
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      # Linter test
      - name: Super-Linter
        uses: github/super-linter@v3.15.5
          
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: 'Dungeon Crawler'
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BRANCH: main
          DISABLE_ERRORS: true
          OUTPUT_FOLDER: Reports
          OUTPUT_DETAILS: detailed
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_JSCPD: false
          VALIDATE_MARKDOWN: false
          unityVersion: 2022.3.22f1
          
     
  test:
    name: Test my project ✨
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      # Test
      - name: Run tests
        uses: game-ci/unity-test-runner@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: 'Dungeon Crawler'
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          unityVersion: 2022.3.22f1
          
  Build:
    name: Build my project ✨
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true
          
      # Build
      - name: Build project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: 'Dungeon Crawler'
          allowDirtyBuild: true
          targetPlatform: WebGL
          unityVersion: 2022.3.22f1

      # Output
      - uses: actions/upload-artifact@v3
        with:
          name: Build
          path: build
