- uses: game-ci/unity-test-runner@v4
  env:
    UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
  with:
    projectPath: https://github.com/Kiopp/Softwere-Development-Repository
    githubToken: ${{ secrets.GITHUB_TOKEN }}
