name: Actions 😎

on: [push, pull_request]

jobs:
  lint:
    name: Test lint
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      # Linter test
      - name: Super-Linter
        uses: super-linter/super-linter@v5.7.2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          DEFAULT_BRANCH: main
          DISABLE_ERROR: true
          VALIDATE_GITLEAKS: false
          VALIDATE_MARKDOWN: false
          VALIDATE_XML: false
          VALIDATE_JSON: false
          VALIDATE_YAML: false
          VALIDATE_JSCPD: false
          VALIDATE_NATURAL_LANGUAGE: false
          VALIDATE_ALL_CODEBASE: false
          PROJECT_PATH: 'Dungeon Crawler'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          UNITY_VERSION: '2022.3.22f1'
          
  test:
    name: Test my project ✨
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      # Test
      - name: Run tests
        uses: game-ci/unity-test-runner@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: 'Dungeon Crawler'
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          unityVersion: 2022.3.22f1
          
  Build:
    name: Build my project ✨
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true
          
      # Build
      - name: Build project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: 'Dungeon Crawler'
          allowDirtyBuild: true
          targetPlatform: StandaloneWindows64
          unityVersion: 2022.3.22f1

      # Output
      - uses: actions/upload-artifact@v3
        with:
          name: Build
          path: build
